# Generated by Django 2.2.16 on 2022-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220413_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Напишите текст комментария', verbose_name='Текст комментария'),
        ),
    ]
